name: Build Artifacts and Publish Elixir Release

on:
  workflow_call:
    inputs:
      test_input:
        required: false
        type: string
      escript:
        required: false
        type: boolean
        default: false

    secrets:
      OTP_VERSION:
        required: true
      ELIXIR_VERSION:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - name: Get the repository name
      id: get_name
      run: echo ::set-output name=value::${GITHUB_REPOSITORY/*\//}

    - name: Get Latest Tag
      id: get_tag
      run: echo ::set-output name=value::$(git describe --tags --abbrev=0)

    - name: Echo Steps
      run: |
        echo input 'test_input': ${{ inputs.test_input }}
        echo step name: ${{ steps.get_name.outputs.value }}
        echo step tag: ${{ steps.get_tag.outputs.value }}
  

    - uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ secrets.ELIXIR_VERSION }}
        otp-version: ${{ secrets.OTP_VERSION }}

    - name: Get Deps
      run: mix deps.get

    - name: Build escript
      if: ${{ inputs.escript }}
      run: mix escript.build

    - name: Build Full Mix Release
      if: ${{ ! inputs.escript }}
      run: echo build mix release

    - name: Publish to AWS S3
      run: aws s3 cp ./${{steps.get_name.outputs.value}} s3://204552664420-release-builds/${{steps.get_name.outputs.value}}/${{steps.get_tag.outputs.value}}/
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1